### ISSUE TITLE
Add and deploy virtual labs from old NaaVRE

### ISSUE THREAD

**Issue by gpelouze** [NaaVRE/NaaVRE-helm#9]
Add all the virtual labs available on old NaaVRE (https://staging.demo.naavre.net/vreapp)

- The virtual labs should use the flavors created by NaaVRE/flavors#7
- All virtual labs should be profiles within a single Jupyter Hub instance
- Users should have a single home directory across virtual labs
- To avoid confusion, virtual labs should show a message warning the users that this is preview version, which might change, and where the data that they create might disappear. This message will be removed once we switch over from the old NaaVRE to the new one (step 3 of QCDIS/projects_overview#383)
- The values for the virtual labs should be reusable across deployments, while still allowing different deployments to not deploy all virtual labs. This can be achieved with the following:

  ```
  NaaVRE-helm
  └── values
      ├── virtual-labs
      │   ├── example-vl.yaml
      │   └── another-vl.yaml
      ├── values-deploy-example-test.yaml
      └── values-deploy-example-staging.yaml
  ```
  
  `values/virtual-labs/*.yaml` contain the virtual lab values. This includes a `enabled=false` field. This allows us to include all the files as helm values, while keeping the files disabled by default. Eg:
  
  ```yaml
  jupyterhub:
    vlabs:
      openlab:
        enabled: false
        slug: openlab
        ...virtual lab configuration
  ```
  
  `values/values-deploy-*.yaml` only sets `.vlabs.[key].enabled=true` to activate virtual labs. Eg:
  
  ```yaml
  jupyterhub:
    vlabs:
      hackathon:
        enabled: true
      openlab:
        enabled: true
  ```

  `values/templates/jupyterhub.yaml` renders the virtual lab's values if `enabled=true`.

  The `helm template` command includes all `values/virtual-labs/*.yaml` as values (`-f`).

**Comment by gpelouze** [comment]
This is partly addressed by #12, but need to add all the virtual labs.

**Comment by gpelouze** [comment]
We also need to use the zfs storage class in our clusters:

```yaml
singleuser:
  storage:
    capacity: 10Gi
    dynamic:
      storageClass: "zfs-generic-nfs"
```

For the helm chart, it should be possible to configure this in the values file.
